### PR TITLE
Service Provider Links on Movie Cards

### PR DESCRIPTION
**Pull request by Steven-matos**
# Description

Part of implementation of #5 

Please add a list of what someone reviewing the PR
should be expecting from this PR.
This will include the

- functionality you created/updated
- packages you added and why you added them
- documentation you added

## Type of change

- [x] New feature (non-breaking change which adds functionality)

## Change Status

- [x] Complete, tested, ready to review and merge
- [ ] Complete, but not tested (may need new tests)
- [ ] Incomplete/work-in-progress, PR is for discussion/feedback

# How Has This Been Tested?

- [x] LocalHost

# Checklist

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] My code has been reviewed by at least one peer
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [x] There are no merge conflicts

### CODE REVIEW

**Comment by Steven-matos** [comment]
Screen Shot 2020-07-21 at 12 11 39 PM
Screen Shot 2020-07-21 at 12 12 03 PM
Screen Shot 2020-07-21 at 12 17 07 PM

**Comment by moviedatascience** [comment]
How difficult would it be to have each icon occupy the same space every time instead of filling from the top with icons?

That way you could quickly scan a page and see where each movie is hosted

**Comment by Steven-matos** [comment]
> How difficult would it be to have each icon occupy the same space every time instead of filling from the top with icons?
> 
> That way you could quickly scan a page and see where each movie is hosted
> 

it wouldn't work since the state for the provider comes in random from the API I hardcoded the buttons in the order that you have them in the image and it does not want to give me the order. It displays the button in the order that they come in. I am able to do even spacing though.

**Comment by moviedatascience** [comment]
Okay sounds good

**Comment by Steven-matos** [comment]
Screen Shot 2020-07-22 at 1 46 08 PM

Final look with even spacing

**Pull request merged**
